version: '3.8'

networks:
  my_network:
    driver: bridge

services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: api
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase?rewriteBatchedStatements=true&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: verysecret
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - mysql
#      - redis
#    networks:
#      - my_network

  mysql:
    image: 'mysql:8.0.39'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - my_network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - my_network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    environment:
      - TZ=Asia/Seoul
