spring:
  config:
    import: optional:file:.env[.properties]
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME}

api_stadium_key: ${API_KEY}
