spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: verysecret
    url: jdbc:mysql://localhost:3306/mydatabase?rewriteBatchedStatements=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&logger=Slf4JLogger&maxQuerySizeToLog=999999&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 800
        order_updates: true
        order_inserts: true
  data:
    redis:
      port: 6379
      host: localhost

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
