ALTER TABLE test_result
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE test_result
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP;

ALTER TABLE test_result
    MODIFY COLUMN deleted_at TIMESTAMP NULL;

CREATE INDEX idx_test_result_age_sex ON test_result (age, sex);


ALTER TABLE person
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE person
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP;

ALTER TABLE person
    MODIFY COLUMN deleted_at TIMESTAMP NULL;


ALTER TABLE member
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE member
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP;

ALTER TABLE member
    MODIFY COLUMN deleted_at TIMESTAMP NULL;
